apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-letsencrypt-demo
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx