version: '3'

services:
  nginx-proxy:
    build: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api

  api:
    build: aspnetapp
    ports:
      - "8181:80"
