version: '3'

services:
  nginx-proxy:
    build: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certificates:ro
    depends_on:
      - api

  api:
    build: app
    ports:
      - "8181:80"
