version: '2'

services:
  nginx-proxy:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  api:
    build: aspnetapp
    ports:
      - "8181:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
