version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates:/etc/nginx/certificates:ro
    entrypoint: nginx -g "daemon off;"
    depends_on:
      - api

  api:
    build: app
    ports:
      - "8181:80"
